// examples/sveltekit-full/src/routes/items/+page.svelte
<script lang="ts">
  import type { PageData, ActionData } from './$types';

  export let data: PageData;
  export let form: ActionData;
</script>

<svelte:head>
  <title>kiwa SvelteKit PoC — items</title>
</svelte:head>

<h1>kiwa SvelteKit PoC</h1>

<p>signed in as: <strong>{data.user ?? 'guest'}</strong> ({data.count} items)</p>

<ul>
  {#each data.items as item (item.id)}
    <li>
      <strong>{item.name}</strong> — tags: {item.tags.join(', ')}
    </li>
  {/each}
</ul>

<h2>Create new item</h2>

<form method="POST" action="?/create">
  <label>
    name: <input type="text" name="name" required minlength="2" />
  </label>
  <button type="submit">create</button>
</form>

{#if form && 'id' in form}
  <p data-testid="create-success">created id={form.id} name={form.name}</p>
{/if}

{#if form && 'field' in form}
  <p data-testid="create-error">error: {form.message}</p>
{/if}

// examples/remix-full/app/routes/items.tsx
// items.tsx — Remix UI route。 thin wrapper として _kiwa の pure loader / action を re-invoke する。

import type { ActionFunctionArgs, LoaderFunctionArgs } from '@remix-run/node';
import { Form, useActionData, useLoaderData } from '@remix-run/react';
import { itemsLoader } from '../lib/_kiwa/items-loader.js';
import { createItemAction } from '../lib/_kiwa/items-action.js';
import type { CreateItemFailure, CreateItemSuccess } from '../lib/_kiwa/items-action.js';
import type { ItemsLoaderData } from '../lib/_kiwa/items-loader.js';

export const loader = async ({ request, params, context }: LoaderFunctionArgs): Promise<Response> => {
  return itemsLoader({ request, params: params as Record<string, string>, context: context as Record<string, unknown> });
};

export const action = async ({ request, params, context }: ActionFunctionArgs): Promise<Response> => {
  return createItemAction({ request, params: params as Record<string, string>, context: context as Record<string, unknown> });
};

export default function ItemsRoute() {
  const data = useLoaderData<ItemsLoaderData>();
  const result = useActionData<CreateItemSuccess | CreateItemFailure>();
  const successResult = result && 'id' in result ? result : null;
  const failureResult = result && 'field' in result ? result : null;

  return (
    <main>
      <h1>kiwa Remix PoC</h1>
      <p>
        signed in as: <strong>{data.user ?? 'guest'}</strong> ({data.count} items)
      </p>
      <ul>
        {data.items.map((item) => (
          <li key={item.id}>
            <strong>{item.name}</strong> — tags: {item.tags.join(', ')}
          </li>
        ))}
      </ul>
      <h2>Create new item</h2>
      <Form method="post">
        <label>
          name: <input type="text" name="name" required minLength={2} />
        </label>
        <button type="submit">create</button>
      </Form>
      {successResult ? (
        <p data-testid="create-success">
          created id={successResult.id} name={successResult.name}
        </p>
      ) : null}
      {failureResult ? (
        <p data-testid="create-error">error: {failureResult.message}</p>
      ) : null}
    </main>
  );
}
